name: Tests
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: VERBOSE=1 make format
      - run: git diff --exit-code
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libasound2-dev libudev-dev
          version: 1.0
      - uses: Swatinem/rust-cache@v2
      - run: VERBOSE=1 make ci
